# site settings
title: EuroMatSoftPolex
subtitle: Software Agency
email: euromatsoftpolex@gmail.com
description: Welcome to EuroMatSoftPolex, your destination for<br />innovative and tailor-made software solutions.
baseurl: / # the subpath of your site, e.g. /blog
url: https://euromatsoftpolex.com # the base hostname & protocol for your site
author: EuroMatSoftPolex
street_address:
city: Cracow
state:
zip_code:
country: Poland
phone: +48 459 240 400

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  # GitHub: https://github.com/andrewbanchich
  GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/company/euromatsoftpolex
  # Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
